"""ContextSync Hooks command group — Install and manage local git hooks."""

from __future__ import annotations

import os
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console

hooks_app = typer.Typer(
    name="hooks",
    help="📋 Install and manage local Git hooks.",
    no_args_is_help=True,
)
console = Console()


def _find_repo_root() -> Path:
    """Find the git repo root from current directory."""
    from git import Repo, InvalidGitRepositoryError

    try:
        repo = Repo(Path.cwd(), search_parent_directories=True)
        return Path(repo.working_tree_dir)
    except InvalidGitRepositoryError:
        console.print("[red]Error:[/red] Not inside a git repository.")
        raise typer.Exit(1)


@hooks_app.command()
def install(
    path: Optional[Path] = typer.Argument(None, help="Project root (default: current directory)"),
    force: bool = typer.Option(False, "--force", "-f", help="Force overwrite pre-commit hook if it exists"),
):
    """Configure a Git pre-commit hook to automatically audit rules on every commit.

    Checks for the presence of a .git folder in the repository root and writes
    an executable .git/hooks/pre-commit script that runs 'contextmesh lint --fail-on-stale'.
    """
    repo_root = (path or _find_repo_root()).resolve()
    git_dir = repo_root / ".git"

    if not git_dir.is_dir():
        console.print("[bold red]Error:[/bold red] Not a git repository or '.git' directory not found.")
        raise typer.Exit(1)

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(exist_ok=True)

    pre_commit_path = hooks_dir / "pre-commit"

    # Script content with robust environment path fallback check
    hook_script = (
        "#!/bin/sh\n"
        "# ContextMesh Git pre-commit hook\n"
        "# Automatically generated by contextmesh hooks install\n\n"
        "echo \"🔍 Auditing AI context and rules before commit...\"\n"
        "if command -v contextmesh >/dev/null 2>&1; then\n"
        "    contextmesh lint --fail-on-stale\n"
        "else\n"
        "    echo \"⚠️ contextmesh not found on PATH. Skipping pre-commit context audit.\"\n"
        "fi\n"
    )

    if pre_commit_path.exists() and not force:
        try:
            content = pre_commit_path.read_text(encoding="utf-8")
        except Exception:
            content = ""
            
        if "contextmesh lint" in content:
            console.print("[yellow]✓ Pre-commit hook is already installed.[/yellow]")
            return
        
        console.print(f"[yellow]⚠️ Existing pre-commit hook detected at {pre_commit_path}[/yellow]")
        append = typer.confirm("Append ContextMesh lint check to the end of the existing hook?", default=True)
        if append:
            try:
                with open(pre_commit_path, "a", encoding="utf-8") as f:
                    f.write("\n# ContextMesh check\nif command -v contextmesh >/dev/null 2>&1; then\n    contextmesh lint --fail-on-stale\nfi\n")
                console.print("[green]✓ ContextMesh hook appended successfully.[/green]")
                return
            except Exception as e:
                console.print(f"[bold red]Error appending to hook file:[/bold red] {e}")
                raise typer.Exit(1)
        else:
            console.print("[yellow]Skipped installing pre-commit hook.[/yellow]")
            return

    # Write new hook script
    try:
        pre_commit_path.write_text(hook_script, encoding="utf-8")
        # Set executable permissions (0o755)
        os.chmod(pre_commit_path, 0o755)
    except Exception as e:
        console.print(f"[bold red]Error writing hook file:[/bold red] {e}")
        raise typer.Exit(1)

    console.print(f"[green]✓ Pre-commit hook successfully installed at {pre_commit_path}[/green]")
