"""Aggregator — compiles the context tree into flat files for backward compatibility."""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from contextsync.config import ContextSyncConfig
from contextsync.core.tree_walker import ContextNode, TreeWalker


class Aggregator:
    """Compiles the hierarchical CONTEXT.md tree into flat files.

    Generates .cursorrules, AGENTS.md, CLAUDE.md etc. by walking
    the tree and concatenating relevant context files.
    """

    def __init__(self, tree_walker: TreeWalker, config: ContextSyncConfig):
        self.tree_walker = tree_walker
        self.config = config

    def aggregate_full(self) -> str:
        """Aggregate the entire tree into a single string."""
        tree = self.tree_walker.build_tree()

        # Find root node
        root = None
        for node in tree.values():
            if node.exists and node.depth == 0:
                root = node
                break

        if root is None:
            return "# No context files found\n"

        parts: list[str] = []
        self._walk_and_collect(root, parts, depth=0)
        return "\n\n---\n\n".join(parts)

    def aggregate_scoped(self, scope_path: Path) -> str:
        """Aggregate only context files relevant to a specific path.

        Loads the ancestor chain + lateral links for focused context.
        """
        chain = self.tree_walker.get_ancestor_chain(scope_path)

        if not chain:
            return "# No context found for this path\n"

        parts: list[str] = []

        # Add context files from most specific to most general
        for node in chain:
            if node.content:
                header = f"<!-- From: {node.dir_path.relative_to(self.tree_walker.repo_root)} -->"
                parts.append(f"{header}\n{node.content}")

        return "\n\n---\n\n".join(parts)

    def generate_cursorrules(self) -> str:
        """Generate a .cursorrules file from the context tree."""
        content = self.aggregate_full()

        return f"""# Project Context (auto-generated by ContextSync)
# Last updated: see individual CONTEXT.md files for timestamps
# Do not edit directly — managed by ContextSync

{content}
"""

    def generate_agents_md(self) -> str:
        """Generate an AGENTS.md file from the context tree."""
        content = self.aggregate_full()

        return f"""# AGENTS.md
<!-- Auto-generated by ContextSync — do not edit directly -->

{content}
"""

    def write_surfaces(self, repo_root: Path) -> list[str]:
        """Write all configured surface files.

        Returns list of written file paths.
        """
        written = []

        for surface in self.config.consumption.aggregator.targets:
            if surface == ".cursorrules":
                output = self.generate_cursorrules()
            elif surface.lower() in ("agents.md", "claude.md"):
                output = self.generate_agents_md()
            else:
                output = self.aggregate_full()

            target_path = repo_root / surface
            target_path.write_text(output, encoding="utf-8")
            written.append(surface)

        return written

    def _walk_and_collect(
        self,
        node: ContextNode,
        parts: list[str],
        depth: int,
    ) -> None:
        """Recursively walk the tree and collect content."""
        if node.exists and node.content:
            parts.append(node.content)

        # Process children sorted by path
        for child in sorted(node.children, key=lambda n: str(n.dir_path)):
            if child.exists:
                self._walk_and_collect(child, parts, depth + 1)
