"""Aggregator — compiles the context tree into flat files for every AI tool.

Generates .cursorrules, CLAUDE.md, GEMINI.md, AGENTS.md,
copilot-instructions.md, .windsurfrules, .clinerules, and
optionally .cursor/rules/*.mdc from the hierarchical CONTEXT.md tree.

Each target gets the SAME context but:
- Formatted for that tool's conventions
- Truncated to its max_lines budget using section priority
- Token-budget-aware: Gotchas/Invariants prioritized over Key Components
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from contextsync.config import AggregatorTarget, ContextSyncConfig
from contextsync.core.section_ranker import rank_and_truncate, rank_multi_file
from contextsync.core.tree_walker import ContextNode, TreeWalker


# ─── Tool-Specific Headers ──────────────────────────────────────────────────

TOOL_HEADERS: dict[str, str] = {
    ".cursorrules": (
        "# Project Context (auto-generated by ContextSync)\n"
        "# Do not edit directly — managed by ContextSync\n"
        "# Regenerate with: contextsync aggregate\n"
    ),
    "CLAUDE.md": (
        "# CLAUDE.md\n"
        "<!-- Auto-generated by ContextSync — do not edit directly -->\n"
        "<!-- Regenerate with: contextsync aggregate -->\n"
    ),
    "GEMINI.md": (
        "# GEMINI.md\n"
        "<!-- Auto-generated by ContextSync — do not edit directly -->\n"
        "<!-- Regenerate with: contextsync aggregate -->\n"
    ),
    "AGENTS.md": (
        "# AGENTS.md\n"
        "<!-- Auto-generated by ContextSync — do not edit directly -->\n"
        "<!-- Regenerate with: contextsync aggregate -->\n"
    ),
    ".github/copilot-instructions.md": (
        "# Copilot Instructions\n"
        "<!-- Auto-generated by ContextSync — do not edit directly -->\n"
    ),
    ".windsurfrules": (
        "# Windsurf Rules (auto-generated by ContextSync)\n"
        "# Do not edit directly — managed by ContextSync\n"
    ),
    ".clinerules": (
        "# Cline Rules (auto-generated by ContextSync)\n"
        "# Do not edit directly — managed by ContextSync\n"
    ),
}


class Aggregator:
    """Compiles the hierarchical CONTEXT.md tree into flat files.

    Generates tool-specific context files by walking the tree,
    ranking sections by AI impact, and truncating to each target's
    token budget.
    """

    def __init__(self, tree_walker: TreeWalker, config: ContextSyncConfig):
        self.tree_walker = tree_walker
        self.config = config

    def aggregate_full(self) -> str:
        """Aggregate the entire tree into a single string."""
        tree = self.tree_walker.build_tree()

        # Find root node
        root = None
        for node in tree.values():
            if node.exists and node.depth == 0:
                root = node
                break

        if root is None:
            return "# No context files found\n"

        parts: list[str] = []
        self._walk_and_collect(root, parts, depth=0)
        return "\n\n---\n\n".join(parts)

    def aggregate_scoped(self, scope_path: Path) -> str:
        """Aggregate only context files relevant to a specific path.

        Loads the ancestor chain + lateral links for focused context.
        """
        chain = self.tree_walker.get_ancestor_chain(scope_path)

        if not chain:
            return "# No context found for this path\n"

        parts: list[str] = []

        # Add context files from most specific to most general
        for node in chain:
            if node.content:
                header = f"<!-- From: {node.dir_path.relative_to(self.tree_walker.repo_root)} -->"
                parts.append(f"{header}\n{node.content}")

        return "\n\n---\n\n".join(parts)

    def generate_for_target(self, target: AggregatorTarget) -> str:
        """Generate content for a specific target with smart truncation.

        Applies section prioritization and respects the target's max_lines.
        """
        # Collect all content from the tree
        tree = self.tree_walker.build_tree()
        contents: list[tuple[str, str]] = []

        root = None
        for node in tree.values():
            if node.exists and node.depth == 0:
                root = node
                break

        if root is None:
            return "# No context files found\n"

        self._collect_contents(root, contents)

        # Get tool-specific header
        header = TOOL_HEADERS.get(target.path, f"# Context ({target.path})\n")
        header_lines = header.count("\n") + 1

        # Budget for content (subtract header)
        content_budget = target.max_lines - header_lines - 2  # 2 for spacing

        # Use rank_multi_file for smart prioritization
        ranked_content = rank_multi_file(contents, content_budget)

        return f"{header}\n{ranked_content}\n"

    # ── Legacy methods (backward compat) ─────────────────────────────────

    def generate_cursorrules(self) -> str:
        """Generate a .cursorrules file from the context tree."""
        target = AggregatorTarget(path=".cursorrules", max_lines=300)
        return self.generate_for_target(target)

    def generate_agents_md(self) -> str:
        """Generate an AGENTS.md file from the context tree."""
        target = AggregatorTarget(path="AGENTS.md", max_lines=800)
        return self.generate_for_target(target)

    # ── Universal Surface Writer ─────────────────────────────────────────

    def write_surfaces(self, repo_root: Path) -> list[str]:
        """Write all configured surface files.

        Returns list of written file paths.
        """
        written = []

        for target in self.config.consumption.aggregator.targets:
            if not target.enabled:
                continue

            output = self.generate_for_target(target)

            # Handle subdirectory targets (e.g., .github/copilot-instructions.md)
            target_path = repo_root / target.path
            target_path.parent.mkdir(parents=True, exist_ok=True)
            target_path.write_text(output, encoding="utf-8")
            written.append(target.path)

        return written

    def write_all_surfaces(self, repo_root: Path) -> list[str]:
        """Write ALL supported surface files (used by --targets all).

        Returns list of written file paths.
        """
        from contextsync.config import ALL_AGGREGATOR_TARGETS

        written = []

        for target in ALL_AGGREGATOR_TARGETS:
            output = self.generate_for_target(target)

            target_path = repo_root / target.path
            target_path.parent.mkdir(parents=True, exist_ok=True)
            target_path.write_text(output, encoding="utf-8")
            written.append(target.path)

        return written

    def write_cursor_v2_rules(self, repo_root: Path) -> list[str]:
        """Generate .cursor/rules/*.mdc files — one per CONTEXT.md node.

        Maps the CONTEXT.md tree 1:1 into Cursor's directory-scoped rules.
        Each .mdc file contains the scoped context for that directory.
        """
        tree = self.tree_walker.build_tree()
        rules_dir = repo_root / ".cursor" / "rules"
        rules_dir.mkdir(parents=True, exist_ok=True)

        written = []

        for node in tree.values():
            if not node.exists or not node.content:
                continue

            # Create a .mdc filename from the directory path
            rel_path = node.dir_path.relative_to(repo_root)
            if str(rel_path) == ".":
                mdc_name = "_root.mdc"
            else:
                mdc_name = str(rel_path).replace("/", "_") + ".mdc"

            # Truncate to 300 lines per rule file
            truncated = rank_and_truncate(node.content, 300)

            # MDC format: frontmatter + content
            glob_pattern = f"{rel_path}/**" if str(rel_path) != "." else "**"
            mdc_content = (
                f"---\n"
                f"description: Context for {rel_path}\n"
                f"globs: {glob_pattern}\n"
                f"alwaysApply: false\n"
                f"---\n\n"
                f"{truncated}\n"
            )

            mdc_path = rules_dir / mdc_name
            mdc_path.write_text(mdc_content, encoding="utf-8")
            written.append(f".cursor/rules/{mdc_name}")

        return written

    # ── Internal helpers ─────────────────────────────────────────────────

    def _walk_and_collect(
        self,
        node: ContextNode,
        parts: list[str],
        depth: int,
    ) -> None:
        """Recursively walk the tree and collect content."""
        if node.exists and node.content:
            parts.append(node.content)

        # Process children sorted by path
        for child in sorted(node.children, key=lambda n: str(n.dir_path)):
            if child.exists:
                self._walk_and_collect(child, parts, depth + 1)

    def _collect_contents(
        self,
        node: ContextNode,
        contents: list[tuple[str, str]],
    ) -> None:
        """Recursively collect (path, content) tuples for ranking."""
        if node.exists and node.content:
            try:
                rel_path = str(node.dir_path.relative_to(self.tree_walker.repo_root))
            except ValueError:
                rel_path = str(node.dir_path)
            contents.append((rel_path if rel_path != "." else "/", node.content))

        for child in sorted(node.children, key=lambda n: str(n.dir_path)):
            if child.exists:
                self._collect_contents(child, contents)
